# Generated by Django 4.0.4 on 2022-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='friday',
        ),
        migrations.AddField(
            model_name='todo',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
